apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tom-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tom-app
    spec:
      containers:
      - name: tomcat-cont
        image: gcr.io/jenkins-project-249206/tomcat:v1
        ports:
        - containerPort: 8080

