apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tomcat
spec:
  replicas: 1
  template:
   metadata:
    labels:
     app: tomcat-app
    spec:
      containers:
      - image: gcr.io/jenkins-project-249206/tomcat:v1
        name: tomcatcont
        ports:
        - name: tomcatcont
          containerPort: 8080
