apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: app-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tomcat
  template:
   metadata:
    labels:
     app: app-tomcat
   spec:
     containers:
     - image: gcr.io/jenkins-project-249206/tomcat:v1
       name: tomcatcont
       ports:
       - name: tomcatcont
         containerPort: 8080
